### Create new user

POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "vanchinhduong2307@gmail.com",
  "password" : "abc1234"
}


### Get All user
GET http://localhost:3000/auth/user
